/** Branch pictures live in /public/images/branches (generated by `npm run samples:build`). Unknown branches get the placeholder. */
const HAVE = new Set([
  "cse", "it", "ece", "eee", "mechanical", "civil", "ai-data-science", "robotics", "mechatronics", "aerospace",
  "automobile", "biomedical", "chemical", "instrumentation", "agricultural", "iot",
]);

export function branchImage(slug: string): string {
  return HAVE.has(slug) ? `/images/branches/${slug}.svg` : "/images/placeholder.svg";
}
