/**
 * Generates everything derived from src/data/sample-projects.ts:
 *   - supabase/seed_sample_projects.sql   (idempotent; never touches products you have taken over)
 *   - public/images/**                    (original SVG illustrations)
 * Run:  npm run samples:build
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { SAMPLE_PROJECTS as BASE_SAMPLES } from "../src/data/sample-projects.ts";
import { MORE_SAMPLE_PROJECTS } from "../src/data/more-sample-projects.ts";

/** The 30 from the brief plus the extra listings that fill every branch. */
const SAMPLE_PROJECTS = [...BASE_SAMPLES, ...MORE_SAMPLE_PROJECTS];
import { BRANCH_ACCENT, fallbackSvg, heroSvg, motifSvg, techTileSvg } from "./lib/art.ts";

/** The 12 sample products created by the original seed.sql, with the picture each one gets (only if it has no image yet). */
export const EXISTING_SAMPLES: Record<string, { motif: string; branch: string }> = {
  "face-recognition-attendance-system": { motif: "eye", branch: "ai-data-science" },
  "mern-elearning-platform": { motif: "dashboard", branch: "cse" },
  "network-intrusion-detection-ml": { motif: "shield", branch: "cse" },
  "smart-grid-iot-monitoring": { motif: "meter", branch: "eee" },
  "g3-building-staad-analysis": { motif: "building", branch: "civil" },
  "drone-flight-controller-design": { motif: "drone", branch: "aerospace" },
  "esp32-home-automation-kit": { motif: "chip", branch: "ece" },
  "line-follower-robot-kit": { motif: "robotcar", branch: "robotics" },
  "solar-tracker-mini-kit": { motif: "solar", branch: "eee" },
  "robotic-arm-4dof-kit": { motif: "arm", branch: "robotics" },
  "arduino-weather-station-kit": { motif: "sensorcloud", branch: "ece" },
  "ecg-sensor-kit": { motif: "ecg", branch: "biomedical" },
};

/** Home-page branch cards (12) and the picture for each. `iot` is a search shortcut, not a database branch. */
export const BRANCH_CARDS: { slug: string; motif: string }[] = [
  { slug: "cse", motif: "dashboard" }, { slug: "ece", motif: "chip" }, { slug: "eee", motif: "solar" },
  { slug: "mechanical", motif: "gear" }, { slug: "civil", motif: "building" }, { slug: "ai-data-science", motif: "brain" },
  { slug: "robotics", motif: "arm" }, { slug: "iot", motif: "sensorcloud" }, { slug: "aerospace", motif: "drone" },
  { slug: "biomedical", motif: "ecg" }, { slug: "chemical", motif: "flask" }, { slug: "agricultural", motif: "plant" },
];

/** Branches that are not on the home page still get a picture for the branch directory. */
const EXTRA_BRANCH_IMAGES: { slug: string; motif: string }[] = [
  { slug: "it", motif: "shield" }, { slug: "mechatronics", motif: "sorter" },
  { slug: "automobile", motif: "evcharge" }, { slug: "instrumentation", motif: "meter" },
];

const NEW_CATEGORIES: [string, string, string, number][] = [
  ["eee", "smart-lighting", "Smart Lighting", 40],
  ["mechanical", "robotics-mechanisms", "Robotics & Mechanisms", 40],
  ["mechanical", "condition-monitoring", "Condition Monitoring", 50],
  ["mechanical", "industrial-automation", "Industrial Automation", 60],
  ["civil", "construction-technology", "Construction Technology", 40],
  ["agricultural", "smart-farming", "Smart Farming", 10],
];

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (a: string[]) => (a.length ? `array[${a.map(q).join(", ")}]::text[]` : "'{}'::text[]");
const paise = (r: number) => Math.round(r * 100);

function write(path: string, content: string) {
  const dir = path.slice(0, path.lastIndexOf("/"));
  mkdirSync(dir, { recursive: true });
  writeFileSync(path, content);
}

// ------------------------------------------------------------------ images
const IMG = "public/images";
write(`${IMG}/hero.svg`, heroSvg());
write(`${IMG}/placeholder.svg`, fallbackSvg());
for (const b of [...BRANCH_CARDS, ...EXTRA_BRANCH_IMAGES]) {
  write(`${IMG}/branches/${b.slug}.svg`, motifSvg(b.motif, BRANCH_ACCENT[b.slug] ?? "#38BDF8", `${b.slug} engineering illustration`, 640, 400));
}
for (const p of SAMPLE_PROJECTS) {
  const accent = BRANCH_ACCENT[p.branch] ?? "#38BDF8";
  write(`${IMG}/projects/${p.slug}.svg`, motifSvg(p.motif, accent, `Illustration for ${p.title}`));
  write(`${IMG}/projects/${p.slug}-tech.svg`, techTileSvg(p.title, accent, p.tech, p.sku));
}
for (const [slug, e] of Object.entries(EXISTING_SAMPLES)) {
  if (SAMPLE_PROJECTS.some((p) => p.slug === slug)) continue;
  write(`${IMG}/projects/${slug}.svg`, motifSvg(e.motif, BRANCH_ACCENT[e.branch] ?? "#38BDF8", `Illustration for ${slug.replace(/-/g, " ")}`));
}

// ------------------------------------------------------------------ SQL
const out: string[] = [];
out.push(`-- ProjectNexa: 43 SAMPLE / DEMO project listings. GENERATED by scripts/build-samples.ts from src/data/sample-projects.ts.
-- Safe to run more than once: it refreshes rows that are still flagged as samples and never touches a product
-- once you have un-flagged it (taken it over as a real product). Run AFTER supabase/seed.sql and migration 08.
-- None of these projects has been built, tested or verified, and no download files exist for them.
`);
out.push(`insert into public.branches (slug, name, short_name, description, sort_order) values
  ('agricultural', 'Agricultural Engineering', 'Agricultural', 'Smart farming, irrigation and agri-automation projects.', 150)
on conflict (slug) do nothing;
`);
out.push(`insert into public.categories (branch_id, slug, name, sort_order)
select b.id, v.slug, v.name, v.sort_order
  from (values
${NEW_CATEGORIES.map(([b, s, n, o]) => `    (${q(b)}, ${q(s)}, ${q(n)}, ${o})`).join(",\n")}
  ) as v(branch_slug, slug, name, sort_order)
  join public.branches b on b.slug = v.branch_slug
on conflict (branch_id, slug) do nothing;
`);

const fresh = SAMPLE_PROJECTS.filter((p) => !p.existingSlug);
const rows = fresh.map((p) => {
  const ptype = p.type === "hardware" ? "hardware" : "digital";
  const cover = `/images/projects/${p.slug}.svg`;
  const gallery = `/images/projects/${p.slug}-tech.svg`;
  return `    (${q(p.slug)}, ${q(p.sku)}, ${q(p.title)}, ${q(p.summary)}, ${q(p.description)}, ${q(ptype)}, ${q(p.branch)}, ${q(p.category)}, ${q(p.subdomain)},
     ${paise(p.priceRupees)}, ${p.mrpRupees ? paise(p.mrpRupees) : "null::int"}, ${q(p.difficulty)}, ${arr(p.tech)}, ${arr(p.tags)}, ${q(p.estimatedTime)},
     ${arr(p.features)}, ${arr(p.deliverables)}, ${arr(p.software)}, ${arr(p.hardware)}, ${q(JSON.stringify(p.faq))}::jsonb,
     ${q(cover)}, ${arr([gallery])}, ${p.weightGrams ?? "null::int"}, ${p.cod ? "true" : "false"}, ${p.featured ? "true" : "false"}, ${p.type === "custom" ? "true" : "false"})`;
});
out.push(`insert into public.products
  (slug, sku, title, summary, description, product_type, status, branch_id, category_id, subdomain,
   price_paise, mrp_paise, difficulty, tech_stack, tags, estimated_time,
   features, deliverables, software_requirements, hardware_requirements, faq,
   cover_image_path, gallery_paths, weight_grams, cod_eligible, is_featured, is_quote_only, is_sample)
select v.slug, v.sku, v.title, v.summary, v.description, v.ptype::public.product_type, 'published', b.id, c.id, v.subdomain,
       v.price, v.mrp, v.difficulty::public.difficulty_level, v.tech, v.tags, v.est,
       v.features, v.deliverables, v.sw, v.hw, v.faq,
       v.cover, v.gallery, v.weight, v.cod, v.featured, v.quote, true
  from (values
${rows.join(",\n")}
  ) as v(slug, sku, title, summary, description, ptype, branch_slug, category_slug, subdomain,
         price, mrp, difficulty, tech, tags, est, features, deliverables, sw, hw, faq,
         cover, gallery, weight, cod, featured, quote)
  join public.branches b on b.slug = v.branch_slug
  join public.categories c on c.branch_id = b.id and c.slug = v.category_slug
on conflict (slug) do update set
  sku = excluded.sku, title = excluded.title, summary = excluded.summary, description = excluded.description,
  subdomain = excluded.subdomain, difficulty = excluded.difficulty, tech_stack = excluded.tech_stack, tags = excluded.tags,
  estimated_time = excluded.estimated_time, features = excluded.features, deliverables = excluded.deliverables,
  software_requirements = excluded.software_requirements, hardware_requirements = excluded.hardware_requirements, faq = excluded.faq,
  cover_image_path = excluded.cover_image_path, gallery_paths = excluded.gallery_paths, is_quote_only = excluded.is_quote_only
  where public.products.is_sample;
`);

// Project 3 already exists in the original seed: enrich it instead of adding a duplicate listing.
for (const p of SAMPLE_PROJECTS.filter((x) => x.existingSlug)) {
  out.push(`update public.products set
  is_sample = true,
  sku = coalesce(sku, ${q(p.sku)}),
  subdomain = coalesce(subdomain, ${q(p.subdomain)}),
  estimated_time = coalesce(estimated_time, ${q(p.estimatedTime)}),
  features = case when cardinality(features) = 0 then ${arr(p.features)} else features end,
  deliverables = case when cardinality(deliverables) = 0 then ${arr(p.deliverables)} else deliverables end,
  software_requirements = case when cardinality(software_requirements) = 0 then ${arr(p.software)} else software_requirements end,
  hardware_requirements = case when cardinality(hardware_requirements) = 0 then ${arr(p.hardware)} else hardware_requirements end,
  faq = case when faq = '[]'::jsonb then ${q(JSON.stringify(p.faq))}::jsonb else faq end,
  cover_image_path = coalesce(cover_image_path, ${q(`/images/projects/${p.slug}.svg`)}),
  gallery_paths = case when cardinality(gallery_paths) = 0 then ${arr([`/images/projects/${p.slug}-tech.svg`])} else gallery_paths end
where slug = ${q(p.existingSlug!)};
`);
}

// The 12 listings from the original seed are samples too. Give them a picture only if they have none.
out.push(`update public.products set is_sample = true where slug in (${Object.keys(EXISTING_SAMPLES).map(q).join(", ")}) and not is_sample;
`);
for (const slug of Object.keys(EXISTING_SAMPLES)) {
  out.push(`update public.products set cover_image_path = ${q(`/images/projects/${slug}.svg`)} where slug = ${q(slug)} and cover_image_path is null;`);
}

// Stock for the new sample kits is deliberately ZERO: we do not advertise stock that does not exist.
const kits = SAMPLE_PROJECTS.filter((p) => p.type === "hardware" && !p.existingSlug).map((p) => q(p.slug));
out.push(`
insert into public.inventory (product_id, quantity_on_hand, low_stock_threshold)
select p.id, 0, 5 from public.products p where p.slug in (${kits.join(", ")})
on conflict (product_id) do nothing;
`);

write("supabase/seed_sample_projects.sql", out.join("\n"));
console.log(`Generated seed SQL for ${SAMPLE_PROJECTS.length} sample projects and their images in ${IMG}.`);
